openapi: 3.0.0
info:
  title: browse_manager
  version: '1.0'
servers:
  - url: 'https://services.utelly.com/browse_manager/v1'
    description: prod
  - url: 'https://staging-services.utelly.com/browse_manager/v1'
    description: staging
  - url: 'https://dev-services.utelly.com/browse_manager/v1'
    description: dev
paths:
  '/content/creative_work/{guid}':
    parameters:
      - schema:
          type: string
        name: guid
        in: path
        required: true
    get:
      summary: Get creative work
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  creative_work:
                    $ref: ../models/CreativeWork.v1.yaml
                  _embedded:
                    type: array
                    items:
                      anyOf:
                        - $ref: ../models/CreativeWork.v1.yaml
              examples: {}
      operationId: v1.creative_work.get
      security:
        - Authorization: []
      parameters:
        - schema:
            type: array
            items:
              type: string
              enum:
                - episodes
                - genres
                - tags
                - availabilities
                - content_ratings
                - contributors
            minItems: 1
          in: query
          name: embed
          explode: false
          description: ''
          style: form
        - schema:
            $ref: ../models/language_field.v1.yaml   
          in: query
          name: languages
          description: ''
      description: ''
components:
  schemas: {}
  securitySchemes:
    Authorization:
      name: Authorization
      type: apiKey
      in: header
