openapi: 3.0.0
info:
  title: browse_manager
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/content/creative_work/{guid}':
    parameters:
      - schema:
          type: string
        name: guid
        in: path
        required: true
    get:
      summary: Get creative work
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  creative_work:
                    $ref: ../models/CreativeWork.v1.yaml
                  _embedded:
                    type: array
                    items:
                      anyOf:
                        - $ref: ../models/CreativeWork.v1.yaml
      operationId: v1.creative_work.get
components:
  schemas: {}
