openapi: 3.0.0
info:
  title: browse_manager
  version: '1.0'
servers:
  - url: 'https://services.utelly.com/browse_manager/v1'
    description: prod
  - url: 'https://staging-services.utelly.com/browse_manager/v1'
    description: staging
  - url: 'https://dev-services.utelly.com/browse_manager/v1'
    description: dev
paths:
  '/content/creative_work/{guid}':
    parameters:
      - schema:
          type: string
        name: guid
        in: path
        required: true
    get:
      summary: Get creative work
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  creative_work:
                    $ref: ../models/CreativeWork.v1.yaml
                  _embedded:
                    type: array
                    items:
                      anyOf:
                        - $ref: ../models/CreativeWork.v1.yaml
              examples: {}
      operationId: v1.creative_work.get
      security:
        - Authorization: []
      parameters:
        - schema:
            type: array
            items:
              type: string
              enum:
                - episodes
                - genres
                - tags
                - availabilities
                - content_ratings
                - contributors
            minItems: 1
          in: query
          name: embeds
          explode: false
          description: ''
          style: form
        - schema:
            type: array
            items:
              type: string
              enum:
                - ab
                - aa
                - af
                - ak
                - sq
                - am
                - ar
                - an
                - hy
                - as
                - av
                - ae
                - ay
                - az
                - bm
                - ba
                - eu
                - be
                - bn
                - bh
                - bi
                - bs
                - br
                - bg
                - my
                - ca
                - ch
                - ce
                - ny
                - zh
                - cv
                - kw
                - co
                - cr
                - hr
                - cs
                - da
                - dv
                - nl
                - dz
                - en
                - eo
                - et
                - ee
                - fo
                - fj
                - fi
                - fr
                - ff
                - gl
                - ka
                - de
                - el
                - gn
                - gu
                - ht
                - ha
                - he
                - hz
                - hi
                - ho
                - hu
                - ia
                - id
                - ie
                - ga
                - ig
                - ik
                - io
                - is
                - it
                - iu
                - ja
                - jv
                - kl
                - kn
                - kr
                - ks
                - kk
                - km
                - ki
                - rw
                - ky
                - kv
                - kg
                - ko
                - ku
                - kj
                - la
                - lb
                - lg
                - li
                - ln
                - lo
                - lt
                - lu
                - lv
                - gv
                - mk
                - mg
                - ms
                - ml
                - mt
                - mi
                - mr
                - mh
                - mn
                - na
                - nv
                - nd
                - ne
                - ng
                - nb
                - nn
                - 'no'
                - ii
                - nr
                - oc
                - oj
                - cu
                - om
                - or
                - os
                - pa
                - pi
                - fa
                - pl
                - ps
                - pt
                - qu
                - rm
                - rn
                - ro
                - ru
                - sa
                - sc
                - sd
                - se
                - sm
                - sg
                - sr
                - gd
                - sn
                - si
                - sk
                - sl
                - so
                - st
                - es
                - su
                - sw
                - ss
                - sv
                - ta
                - te
                - tg
                - th
                - ti
                - bo
                - tk
                - tl
                - tn
                - to
                - tr
                - ts
                - tt
                - tw
                - ty
                - ug
                - uk
                - ur
                - uz
                - ve
                - vi
                - vo
                - wa
                - cy
                - wo
                - fy
                - xh
                - yi
                - yo
                - za
                - zu
            minItems: 1
          in: query
          name: languages
          description: ''
          style: form
        - schema:
            type: array
            items:
              type: string
              enum:
                - titles
                - descriptions
                - artworks
                - contributors
                - genres
                - tags
                - availabilities
                - content_ratings
                - episodes
            minItems: 1
          in: query
          name: fields
      description: ''
components:
  schemas: {}
  securitySchemes:
    Authorization:
      name: Authorization
      type: apiKey
      in: header
