openapi: 3.0.0
info:
  title: browse_manager
  version: '1.0'
servers:
  - url: 'https://services.utelly.com/browse_manager/v1'
    description: prod
  - url: 'https://staging-services.utelly.com/browse_manager/v1'
    description: staging
  - url: 'https://dev-services.utelly.com/browse_manager/v1'
    description: dev
paths:
  '/content/creative_works/{guid}':
    parameters:
      - schema:
          type: string
        name: guid
        in: path
        required: true
    get:
      summary: Get a creative work
      tags:
        - Creative work management
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  creative_work:
                    $ref: ../models/CreativeWork.v1.yaml
                  _embedded:
                    type: array
                    items:
                      anyOf:
                        - $ref: ../models/CreativeWork.v1.yaml
                        - $ref: ../models/Genre.v1.yaml
                        - $ref: ../models/ContentRating.v1.yaml
                        - $ref: ../models/Availability.v1.yaml
                        - $ref: ../models/Tag.v1.yaml
                        - $ref: ../models/Service.v1.yaml
                required:
                  - creative_work
              examples: {}
      operationId: v1.content.creative_works.get_one
      security:
        - Authorization: []
      parameters:
        - schema:
            type: array
            items:
              type: string
              enum:
                - parents
                - genres
                - tags
                - availabilities
                - content_ratings
                - contributors
                - services
            minItems: 1
          in: query
          name: embed
          explode: false
          description: ''
          style: form
        - schema:
            type: array
            items:
              $ref: '#/components/schemas/SetLanguages'
            minItems: 1
          in: query
          name: languages
          description: ''
          style: form
        - schema:
            type: array
            items:
              type: string
              enum:
                - titles
                - descriptions
                - artworks
                - contributors
                - genres
                - tags
                - availabilities
                - content_ratings
                - parents
            minItems: 1
          in: query
          name: fields
      description: ''
  /content/creative_works:
    get:
      summary: List creative works
      tags:
        - Creative work management
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  creative_works:
                    type: array
                    items:
                      $ref: ../models/CreativeWork.v1.yaml
      operationId: v1.content.creative_works.get_list
      description: ''
      security:
        - Authorization: []
      parameters:
        - schema:
            type: array
            items:
              type: string
              enum:
                - created_at
                - '-created_at'
                - updated_at
                - '-updated_at'
          in: query
          name: sort
          style: form
        - schema:
            type: integer
            maximum: 50
            minimum: 0
          in: query
          name: limit
        - schema:
            type: integer
          in: query
          name: offset
        - schema:
            type: array
            items:
              $ref: '#/components/schemas/SetLanguages'
          in: query
          name: languages
          style: form
components:
  schemas:
    SetLanguages:
      type: string
      enum:
        - ab
        - aa
        - af
        - ak
        - sq
        - am
        - ar
        - an
        - hy
        - as
        - av
        - ae
        - ay
        - az
        - bm
        - ba
        - eu
        - be
        - bn
        - bh
        - bi
        - bs
        - br
        - bg
        - my
        - ca
        - ch
        - ce
        - ny
        - zh
        - cv
        - kw
        - co
        - cr
        - hr
        - cs
        - da
        - dv
        - nl
        - dz
        - en
        - eo
        - et
        - ee
        - fo
        - fj
        - fi
        - fr
        - ff
        - gl
        - ka
        - de
        - el
        - gn
        - gu
        - ht
        - ha
        - he
        - hz
        - hi
        - ho
        - hu
        - ia
        - id
        - ie
        - ga
        - ig
        - ik
        - io
        - is
        - it
        - iu
        - ja
        - jv
        - kl
        - kn
        - kr
        - ks
        - kk
        - km
        - ki
        - rw
        - ky
        - kv
        - kg
        - ko
        - ku
        - kj
        - la
        - lb
        - lg
        - li
        - ln
        - lo
        - lt
        - lu
        - lv
        - gv
        - mk
        - mg
        - ms
        - ml
        - mt
        - mi
        - mr
        - mh
        - mn
        - na
        - nv
        - nd
        - ne
        - ng
        - nb
        - nn
        - no
        - ii
        - nr
        - oc
        - oj
        - cu
        - om
        - or
        - os
        - pa
        - pi
        - fa
        - pl
        - ps
        - pt
        - qu
        - rm
        - rn
        - ro
        - ru
        - sa
        - sc
        - sd
        - se
        - sm
        - sg
        - sr
        - gd
        - sn
        - si
        - sk
        - sl
        - so
        - st
        - es
        - su
        - sw
        - ss
        - sv
        - ta
        - te
        - tg
        - th
        - ti
        - bo
        - tk
        - tl
        - tn
        - to
        - tr
        - ts
        - tt
        - tw
        - ty
        - ug
        - uk
        - ur
        - uz
        - ve
        - vi
        - vo
        - wa
        - cy
        - wo
        - fy
        - xh
        - yi
        - yo
        - za
        - zu
  securitySchemes:
    Authorization:
      name: Authorization
      type: apiKey
      in: header
